#! /bin/sh
### BEGIN INIT INFO
# Provides:          hostapd-statistics
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog	$network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hostapd-statistics
# Description:       Provide statistics for a Hostapd Hotspot
#
### END INIT INFO

# Author: Soeren Beye <soeren@soerenbeye.de>
#

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Hostapd-statistics"
NAME=hostapd-statistics.sh
DAEMON=/usr/bin/hostapd-statistics/$NAME
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/hostapd-statistics
DAEMON_OPTS=""

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --start --oknodo --quiet --exec "$DAEMON_SBIN" \
		--pidfile "$PIDFILE" -- $DAEMON_OPTS >/dev/null
	log_end_msg "$?"
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --oknodo --quiet --exec "$DAEMON_SBIN" \
		--pidfile "$PIDFILE"
	log_end_msg "$?"
	;;
  restart)
  	$0 stop
	sleep 8
	$0 start
	;;
  status)
	status_of_proc "$DAEMON_SBIN" "$NAME"
	exit $?
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0

